// tests/test_vdf.cpp — VDF parser unit tests.
#include <cassert>
#include <filesystem>
#include <fstream>
#include <iostream>

#include "platform/Vdf.h"

namespace fs = std::filesystem;
using mojave::platform::Vdf::ParseLibraryFolders;

int main() {
    const fs::path base = fs::temp_directory_path() / "mojave_vdf_test";
    fs::remove_all(base);
    fs::create_directories(base);

    const fs::path vdf = base / "libraryfolders.vdf";
    {
        std::ofstream f(vdf);
        f << "\"libraryfolders\"\n{\n"
          << "  \"0\"\n  {\n    \"path\" \"/mnt/games/SteamLibrary\"\n"
          << "    \"label\" \"games\"\n  }\n"
          << "  \"1\"\n  {\n    \"path\" \"/home/u/.local/share/Steam\"\n"
          << "    \"label\" \"\"\n  }\n"
          << "}\n";
    }
    auto libs = ParseLibraryFolders(vdf);
    assert(libs.size() == 2 && "must parse both library entries");
    assert(libs[0] == fs::path("/mnt/games/SteamLibrary"));
    assert(libs[1] == fs::path("/home/u/.local/share/Steam"));
    std::cout << "PASS: VDF parses two libraries\n";

    // Comment handling.
    {
        std::ofstream f(vdf);
        f << "// generated by steam\n"
          << "\"libraryfolders\"\n{\n"
          << "  \"0\" { \"path\" \"/one\" } // inline comment\n"
          << "}\n";
    }
    auto libs2 = ParseLibraryFolders(vdf);
    assert(libs2.size() == 1 && libs2[0] == fs::path("/one"));

    fs::remove_all(base);
    std::cout << "ALL VDF TESTS PASSED\n";
    return 0;
}
